postgres:
  image: postgres:9.4
  ports:
    - "5432:5432"
  volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
myapp:
  image: jlgm/game-api:latest
  ports:
    - "8000:8000"
  links:
    - postgres
  

  # docker-compose up -f docker/docker-compose 
